name: build HelloWorld with gradle and publish it to Dockerhub

on:
  push:
    branches: [ "master" ]

jobs:
  increment version, build and push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Check out code

      - name: Increment Version
        run: |
          VERSION=$(grep "version =" build.gradle.kts | awk -F '"' '{print $2}')
          echo "Current version is : $VERSION"
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
          PATCH=$((PATCH + 1))
          NEW_VERSION="$MAJOR.$MINOR.$PATCH"
          sed -i "s/version = \".*\"/version = \"$NEW_VERSION\"/" build.gradle.kts
          echo "Version incremented to: $NEW_VERSION"
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Commit and Push Changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add build.gradle.kts
          git commit -m "Incremented version to $NEW_VERSION [skip ci]"
          git push origin master
