name: build HelloWorld with gradle and publish it to Dockerhub

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./.scripts

    steps:
    - uses: actions/checkout@v4
      name: Check out code

    - name: Increment Version
      run: chmod +x ./increment_version.sh
